---
# Galazy collections user guide
# https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
#
# To install collections:
# ansible-galaxy collection install -r requirements.yml

collections:
  - name: ansible.posix
    version: 1.4.0

  - name: community.general
    version: 6.0.1
