---
# base
# apply to all
- hosts: all
  become: yes
  roles:
    - base

# dev
- hosts: dev.localdomain.lan
  become: yes
  roles:
    - docker # to be able to use docker context
    - dev
  tags: dev

# docker
# apply 'docker' role on 'dockerhosts' hostgroup
- hosts: dockerhosts
  become: yes
  roles:
    - docker

# reverse proxy
# apply to vm 'reverse-proxy'
- hosts: reverse-proxy.localdomain.lan
  become: yes
  roles:
    - reverse-proxy
