---
# base
- hosts: all
  become: yes
  roles:
    - base

# docker
- hosts: dockerhosts
  become: yes
  roles:
    - docker

# reverse proxy
- hosts: reverse-proxy.localdomain.lan
  become: yes
  roles:
    - reverse-proxy
