---
# tasks file for roles/ssh


- name: block root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin(\\s)"
    line: "PermitRootLogin no"
    state: present
  notify: restart sshd

- name: configured allowed users
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^AllowUsers(\\s)"
    line: "AllowUsers packer amsoares"
    state: present
  notify: restart sshd

- name: set protocol to 2
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Protocol(\\s)"
    line: "Protocol 2"
    state: present
  notify: restart sshd
