# based on guide from: https://docs.docker.com/engine/install/centos/

- name: add docker repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: "Docker CE Stable - $basearch"
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  notify: restart docker

- name: add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ dockerusers }}"
